// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Districts = sequelize.define('districts', {
    nameEn: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    nameTh: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    nameJp: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    nameKr: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    oldDistrictCode: {
      type: DataTypes.STRING,
    },
    location: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'districts',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Districts.associate = (models) => {
    Districts.belongsTo(models.cities, {
      foreignKey: {
        name: 'cityIdKey',
        field: 'city_id',
      },
      as: 'city',
    });
    Districts.hasMany(models.landmarks, {
      foreignKey: {
        name: 'districtIdKey',
        field: 'district_id',
      },
      as: 'landmarks',
    });
    Districts.hasMany(models.bookingSiteAddresses, {
      foreignKey: {
        name: 'districtIdKey',
        field: 'district_id',
      },
      as: 'bookingSiteAddresses',
    });
    Districts.hasMany(models.siteAddresses, {
      foreignKey: {
        name: 'districtIdKey',
        field: 'district_id',
      },
      as: 'siteAddresses',
    });
  };

  return Districts;
};
