// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const OrdersHistory = sequelize.define('ordersHistory', {
    status: {
      type: DataTypes.ENUM(
        'PENDING',
        'CONFIRMED',
        'COMPLETED',
        'CANCELLED',
      ),
      allowNull: false,
    },
    note: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
  }, {
    tableName: 'orders_history',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  OrdersHistory.associate = (models) => {
    OrdersHistory.belongsTo(models.bookings, {
      foreignKey: {
        name: 'bookingIdKey',
        field: 'booking_id',
      },
      as: 'booking',
    });
    OrdersHistory.belongsTo(models.users, {
      foreignKey: {
        name: 'changedByKey',
        field: 'changed_by',
      },
      as: 'changedBy',
    });
    OrdersHistory.belongsTo(models.orders, {
      foreignKey: {
        name: 'orderIdKey',
        field: 'order_id',
      },
      as: 'order',
    });
  };

  return OrdersHistory;
};
