// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const PromotionsRedeem = sequelize.define('promotionsRedeem', {
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
  }, {
    tableName: 'promotions_redeem',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  PromotionsRedeem.associate = (models) => {
    PromotionsRedeem.belongsTo(models.bookings, {
      foreignKey: {
        name: 'bookingIdKey',
        field: 'booking_id',
      },
      as: 'booking',
    });
    PromotionsRedeem.belongsTo(models.bookingsPromotions, {
      foreignKey: {
        name: 'bookingPromotionIdKey',
        field: 'booking_promotion_id',
      },
      as: 'bookingPromotion',
    });
    PromotionsRedeem.belongsTo(models.users, {
      foreignKey: {
        name: 'customerIdKey',
        field: 'customer_id',
      },
      as: 'customer',
    });
    PromotionsRedeem.belongsTo(models.promotions, {
      foreignKey: {
        name: 'promotionIdKey',
        field: 'promotion_id',
      },
      as: 'promotion',
    });
    PromotionsRedeem.belongsTo(models.renewals, {
      foreignKey: {
        name: 'renewalIdKey',
        field: 'renewal_id',
      },
      as: 'renewal',
    });
  };

  return PromotionsRedeem;
};
