// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Providers = sequelize.define('providers', {
    taxId: {
      type: DataTypes.STRING,
    },
    updatedBy: {
      type: DataTypes.INTEGER,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    bankAccountNumber: {
      type: DataTypes.STRING,
    },
    bankAccountHolderName: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'providers',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Providers.associate = (models) => {
    Providers.belongsTo(models.platformBanks, {
      foreignKey: {
        name: 'bankIdKey',
        field: 'bank_id',
      },
      as: 'bank',
    });
    Providers.hasOne(models.users, {
      foreignKey: {
        name: 'providerIdKey',
        field: 'provider_id',
      },
      as: 'user',
    });
  };

  return Providers;
};
