// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const RefreshTokens = sequelize.define('refreshTokens', {
    tokenId: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    refreshTokenHash: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    refreshTokenExpiresAt: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    platform: {
      type: DataTypes.ENUM(
        'IOS',
        'WEB_DESKTOP',
        'WEB_MOBILE',
        'ANDROID',
      ),
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
  }, {
    tableName: 'refresh_tokens',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  RefreshTokens.associate = (models) => {
    RefreshTokens.belongsTo(models.users, {
      foreignKey: {
        name: 'userIdKey',
        field: 'user_id',
      },
      as: 'user',
    });
  };

  return RefreshTokens;
};
