// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Terminations = sequelize.define('terminations', {
    moveOutDate: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    terminationDate: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    failedRenewalsAmount: {
      type: DataTypes.DOUBLE,
      defaultValue: "0",
      allowNull: false,
    },
    remainingDaysAmount: {
      type: DataTypes.DOUBLE,
      defaultValue: "0",
      allowNull: false,
    },
    noticePeriodAmount: {
      type: DataTypes.DOUBLE,
      defaultValue: "0",
      allowNull: false,
    },
    promotionAmount: {
      type: DataTypes.DOUBLE,
      defaultValue: "0",
      allowNull: false,
    },
    discount: {
      type: DataTypes.DOUBLE,
      defaultValue: "0",
      allowNull: false,
    },
    totalAmount: {
      type: DataTypes.DOUBLE,
      defaultValue: "0",
      allowNull: false,
    },
    currency: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    status: {
      type: DataTypes.ENUM(
        'REQUESTED',
        'SCHEDULED',
        'ON_HOLD',
        'TERMINATED',
      ),
      defaultValue: "REQUESTED",
      allowNull: false,
    },
    paymentStatus: {
      type: DataTypes.ENUM(
        'PENDING',
        'PAID',
        'FAILED',
      ),
      defaultValue: "PENDING",
      allowNull: false,
    },
    isOverdue: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      allowNull: false,
    },
    isAutoCreated: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
  }, {
    tableName: 'terminations',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Terminations.associate = (models) => {
    Terminations.belongsTo(models.bookings, {
      foreignKey: {
        name: 'bookingIdKey',
        field: 'booking_id',
      },
      as: 'booking',
    });
    Terminations.belongsTo(models.renewals, {
      foreignKey: {
        name: 'lastRenewalIdKey',
        field: 'last_renewal_id',
      },
      as: 'lastRenewal',
    });
    Terminations.hasMany(models.transactions, {
      foreignKey: {
        name: 'terminationIdKey',
        field: 'termination_id',
      },
      as: 'transactions',
    });
  };

  return Terminations;
};
